apiVersion: v1
data:
  tls.p256.cert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJLekNCMHFBREFnRUNBaEJkMStHaHZPWFYvRTFVUHJNVjBrUXlNQW9HQ0NxR1NNNDlCQU1DTUJzeEdUQVgKQmdOVkJBTU1FRWhUVFNCVGFXMTFiR0YwYjNJZ1EwRXdJQmNOTnpBd01UQXhNREF3TURBd1doZ1BNak16TnpBeApNREV3TURBd01EQmFNQk14RVRBUEJnTlZCQU1NQ0hSc2N5NXdNalUyTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJCnpqMERBUWNEUWdBRW91TWd1dXhyOFJHeFc0TjJKWTJyZDhTSVFsd2hRNjJhcjdTd2F2c0xzc2tQYlZjVDZ4clAKOCs1K2IxTmVHbmFMQjBzaXYvaE40SlFJMjNBdEQrZVFYREFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUJESng5MgoxZnRTRlY1QlQwajdtZmZ5ZVRBakdJeXQ3MlNBYXVMbFVYd0lUZ0loQU9lQTIxVHJGRWhVZHRmZk1RTGJjaFI1CmpNTHQ3MTg1NEpubXBQb1dQbXZxCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
kind: Secret
metadata:
  name: hsm-tls
