{{- /* vim: set ft=helm: */ -}}
{{- /* NIC mergeable master for zeta-guard */ -}}
{{- if .Values.ingressEnabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zeta-guard
  labels:
    {{- include "ingress.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.nginxIngressEnabled }}
    nginx.org/mergeable-ingress-type: "master"
    {{- end }}
    {{- if and .Values.authserver.hostname }}
    {{- if not (and .Values.nginxIngressEnabled .Values.nginxIngressHsm) }}
    cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer | default "letsencrypt" | quote }}
    cert-manager.io/private-key-algorithm: ECDSA
    cert-manager.io/private-key-size: "256"
    {{- end }}
    {{- if not .Values.nginxIngressEnabled }}
    nginx.org/ssl-redirect: "true"
    {{- end }}
    {{- if .Values.nginxIngressEnabled }}
    nginx.org/hsts: "true"
    nginx.org/hsts-max-age: "31536000"
    nginx.org/hsts-include-subdomains: "true"
    {{- end }}
    {{- end }}
    {{- with .Values.ingressMasterAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  {{- if (and .Values.authserver.hostname (not (and .Values.nginxIngressEnabled .Values.nginxIngressHsm))) }}
  tls:
    - hosts:
        - {{ .Values.authserver.hostname | quote }}
      secretName: "zeta-guard-tls"
  {{- end }}
  {{- if .Values.authserver.hostname }}
  rules:
    - host: {{ .Values.authserver.hostname | quote }}
  {{- end }}
{{- end }}
