{{- /* vim: set ft=helm: */ -}}
{{- /* NIC mergeable minion for zeta-guard rules */ -}}
{{- if .Values.ingressEnabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zeta-guard-minion
  labels:
    {{- include "ingress.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.nginxIngressEnabled }}
    nginx.org/mergeable-ingress-type: "minion"
    nginx.org/websocket-services: {{ .Values.routeViaTigerProxy | ternary "tiger-proxy" "pep-proxy-svc" }}
    {{- if .Values.ingress.sessionAffinity.enabled }}
    nginx.org/lb-method: "hash $http_x_forwarded_for consistent"
    {{- end }}
    {{- if and (or .Values.authserver.hsm.tls.enabled .Values.authserver.tls.enabled) (not .Values.routeViaTigerProxy) }}
    nginx.org/ssl-services: "authserver"
    {{- end }}
    {{- end }}
    {{- with .Values.ingressMinionAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  {{- if .Values.openshiftIngress.enabled }}
  tls:
    - hosts:
        - {{ .Values.authserver.hostname | quote }}
      secretName: {{ .Values.openshiftIngress.certName }}
  {{- end }}
  rules:
    - {{- if .Values.authserver.hostname }}
      host: {{ .Values.authserver.hostname | quote }}
      {{- end }}
      http:
        paths:
          {{- if not .Values.authserver.adminHostname }}
          - path: /auth
            pathType: Prefix
            backend:
              service:
                {{- if .Values.routeViaTigerProxy }}
                name: tiger-proxy
                port:
                  number: 80
                {{- else }}
                name: authserver
                port:
                  {{- if or .Values.authserver.hsm.tls.enabled .Values.authserver.tls.enabled }}
                  name: https
                  {{- else }}
                  name: http
                  {{- end }}
                {{- end }}
          {{- end }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.routeViaTigerProxy | ternary "tiger-proxy" "pep-proxy-svc" }}
                port:
                  number: 80
{{- end }}
