{{- if .Values.signing.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.signing.secretName | quote }}
  labels:
    app.kubernetes.io/name: zeta-cert-validation-mock
type: Opaque
data:
  smb-signing-keystore: {{ .Values.signing.smb.keyStore | quote }}
  smb-signing-keystore-password: {{ .Values.signing.smb.keyStorePassword | quote }}
  tls-signing-keystore: {{ .Values.signing.tls.keyStore | quote }}
  tls-signing-keystore-password: {{ .Values.signing.tls.keyStorePassword | quote }}
{{- end }}
