{{- /* vim: set ft=helm: */ -}}
{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hsm-sim
  labels:
    {{- include "hsm-sim.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "hsm-sim.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hsm-sim.labels" . | nindent 8 }}
      {{- if .Values.devMode }}
      annotations:
        zeta.dev/rollout-timestamp: "{{ now | unixEpoch }}"
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets | default .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.resources }}
      resources:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: hsm-sim
          image: "{{ include "hsm-sim.image" . | trim }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          args: ["--listen", "0.0.0.0:50051", "--keys-dir", "/etc/hsm_sim/keys/"]
          ports:
            - containerPort: 50051
              name: grpc
          readinessProbe:
            grpc:
              port: 50051
            initialDelaySeconds: 1
            periodSeconds: 1
          livenessProbe:
            grpc:
              port: 50051
            initialDelaySeconds: 1
            periodSeconds: 10
          {{- with .Values.containerSecurityContext }}
          securityContext:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: keys
              mountPath: /etc/hsm_sim/keys
      initContainers:
        - name: seed-keys
          image: "{{ include "hsm-sim.image" . | trim }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          command: ["sh", "-c", "cp -r /etc/hsm_sim/keys/. /seed-keys/"]
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: keys
              mountPath: /seed-keys

          {{- if .Values.extraKeys.enabled }}
            {{- range $item := .Values.extraKeys.items }}
            - name: extra-keys
              mountPath: /seed-keys/{{ $item | quote }}
              subPath: {{ $item | quote }}
            {{- end }}
          {{- end }}
      volumes:
        - name: keys
          emptyDir: {}
      {{- if .Values.extraKeys.enabled }}
        - name: extra-keys
          secret:
            secretName: {{ .Values.extraKeys.secret }}
      {{- end }}

      securityContext:
        seccompProfile:
          type: RuntimeDefault
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: hsm-sim
  labels:
    {{- include "hsm-sim.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "hsm-sim.selectorLabels" . | nindent 4 }}
  ports:
    - port: 50051
      targetPort: grpc
      name: grpc
{{- end }}
