{{- if and .Values.global.infinispanExternal.enabled (not .Values.global.infinispanExternal.remote.host) (not .Values.global.infinispanExternal.remote.port)}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: infinispan
spec:
  replicas: {{.Values.global.infinispanExternal.replicaCount}}
  selector:
    matchLabels:
      app: infinispan
  template:
    metadata:
      labels:
        app: infinispan
    spec:
      {{- if .Values.global.infinispanExternal.serviceAccount.create }}
      serviceAccountName: {{ .Values.global.infinispanExternal.serviceAccount.name }}
      automountServiceAccountToken: false
      {{- end }}
      {{- with .Values.global.infinispanExternal.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: infinispan
          image: "{{ .Values.global.infinispanExternal.image.repository }}:{{ .Values.global.infinispanExternal.image.tag }}"
          ports:
            - containerPort: 11222
            - containerPort: 7800
          args:
            - "--server-config=/server/conf-custom/infinispan-config.xml"
          env:
            - name: USER
              valueFrom:
                secretKeyRef:
                  {{- if .Values.global.infinispanExternal.admin.secretName }}
                  name: {{ .Values.global.infinispanExternal.admin.secretName }}
                  {{- else }}
                  name: infinispan-admin
                  {{- end }}
                  key: username
            - name: PASS
              valueFrom:
                secretKeyRef:
                  {{- if .Values.global.infinispanExternal.admin.secretName }}
                  name: {{ .Values.global.infinispanExternal.admin.secretName }}
                  {{- else }}
                  name: infinispan-admin
                  {{- end }}
                  key: password
            - name: JAVA_OPTIONS
              value: >-
                -Djgroups.dns.query=infinispan
                -Djgroups.dns.record.type=A
                -Dinfinispan.cluster.name=k8s-cluster
                -Dinfinispan.cluster.stack=kubernetes
                {{- with .Values.global.infinispanExternal.extraJavaOptions }}
                {{ . | trim }}
                {{- end }}
          volumeMounts:
            - name: infinispan-config
              mountPath: /server/conf-custom/
          {{- with .Values.global.infinispanExternal.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.global.infinispanExternal.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: infinispan-config
          configMap:
            name: infinispan-config
{{- end}}
