{{- if and .Values.pepproxy.serviceAccount .Values.pepproxy.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.pepproxy.serviceAccount.name }}
  labels:
    {{- include "pep-proxy.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
