{{ if .Values.opa.enabled -}}

{{- if not .Values.opa.bundle.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-policy
  labels:
    {{- include "opa.labels" . | nindent 4 }}
data:
  authz.rego: |
    {{- include "opa.policyRego" . | nindent 4 }}
{{- end }}

{{- if or .Values.opaPolicy.logDecisions .Values.opa.bundle.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-config
  labels:
    {{- include "opa.labels" . | nindent 4 }}
data:
  opa.yaml: |
    {{- $opaConfig := "" }}
    {{- if .Values.opa.bundle.enabled }}
      {{- $opaConfig = include "opa.bundleConfigYaml" . }}
    {{- else }}
      {{- $opaConfig = include "opa.configYaml" . }}
    {{- end }}
    {{- $opaConfig | nindent 4 }}

{{- if .Values.opa.simulation.enabled  }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-simulation-config
  labels:
    {{- include "opaSimulation.labels" . | nindent 4 }}
data:
  opa.yaml: |
    {{- $opaSimulationConfig := "" }}
    {{- if .Values.opa.bundle.enabled }}
      {{- $opaSimulationConfig = include "opa.bundleConfigYaml" (dict "ctx" . "bundleResource" (include "opa.simBundleResource" .)) }}
    {{- else }}
      {{- $opaSimulationConfig = include "opa.configYaml" . }}
    {{- end }}
    {{- $rectifiedOpaSimulationConfig := mergeOverwrite (fromYaml $opaSimulationConfig) (fromYaml (include "opa-simulation.config" .)) | toYamlPretty }}
    {{- $rectifiedOpaSimulationConfig | nindent 4 }}

{{- end }}

{{- end }}

{{- end }}
