{{- if and .Values.authserver.serviceAccount .Values.authserver.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.authserver.serviceAccount.name }}
  labels:
    {{- include "authserver.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
