apiVersion: apps/v1
kind: Deployment
metadata:
  name: tiger-proxy
  labels:
    {{- include "tiger-proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tiger-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if .Values.devMode }}
      annotations:
        zeta.dev/rollout-timestamp: "{{ now | unixEpoch }}"
      {{- end }}
      labels:
        {{- include "tiger-proxy.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      automountServiceAccountToken: false
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets | default .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: nginx-sidecar
          image: "{{ .Values.nginxSidecar.image.registry | default "" }}{{ .Values.nginxSidecar.image.repository | default "nginxinc/nginx-unprivileged" }}:{{ .Values.nginxSidecar.image.tag | default "alpine3.22-slim" }}"
          imagePullPolicy: "{{ .Values.nginxSidecar.imagePullPolicy }}"
          ports:
            - name: otlp-http-port
              containerPort: 4138
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.nginxSidecar.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tiger-application-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: nginx-tmp
              mountPath: /tmp

        - name: {{ .Chart.Name }}
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ default (printf "%s%s" .Values.global.registry_host .Values.registry_name) .Values.image.registry }}{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          # TODO - review necessity of this section or rework
          ports:
            - name: proxy-port
              containerPort: {{ .Values.proxyConfig.proxyPort }}
            - name: admin-port
              containerPort: {{ .Values.proxyConfig.adminPort }}
          livenessProbe:
            httpGet:
              path: {{ .Values.startup.livenessProbe.url }}
              port: {{ .Values.startup.livenessProbe.port }}
            failureThreshold: {{ default .Values.startup.failureThreshold .Values.startup.livenessProbe.failureThreshold }}
            periodSeconds: {{ default .Values.startup.startupPeriodSeconds .Values.startup.livenessProbe.periodSeconds }}
            initialDelaySeconds: {{ default 120 .Values.startup.livenessProbe.initialDelaySeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.startup.readinessProbe.url }}
              port: {{ .Values.startup.readinessProbe.port }}
            failureThreshold: {{ default .Values.startup.failureThreshold .Values.startup.readinessProbe.failureThreshold }}
            periodSeconds: {{ default .Values.startup.startupPeriodSeconds .Values.startup.readinessProbe.periodSeconds }}
            initialDelaySeconds: {{ default 120 .Values.startup.readinessProbe.initialDelaySeconds }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tiger-application-config
              mountPath: /app/application.yaml
              subPath: "application.yaml"
              readOnly: true
            - name: maven-target
              mountPath: /app/target
            - name: tmp
              mountPath: /tmp

      volumes:
        - name: tiger-application-config
          configMap:
            name: tiger-proxy
            items:
            - key: application.yaml
              path: application.yaml
            - key: application.grpc.yaml
              path: application.grpc.yaml
            - key: nginx.conf
              path: nginx.conf
        - name: maven-target
          emptyDir: {}
        - name: nginx-tmp
          emptyDir: {}
        - name: tmp
          emptyDir: {}
