global: {}

enabled: true
registry_name: ""
image:
  repository: hsm_sim
  tag: 1.0.0
imagePullPolicy: Always
imagePullSecrets: [ ]
podLabels: {}
resources:
  limits:
    memory: "100Mi"
  requests:
    memory: "10Mi"
extraKeys:
  enabled: false
  secret: hsm-tls
  # items:
  # - tls.p256.key.pem
  # - tls.p256.cert.pem
  items: []
devMode: false
podAnnotations: {}
affinity: {}
tolerations: []
containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  capabilities:
    drop: [ "ALL" ]
